version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - networkOne

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - networkOne

  db:
    container_name: mongo
    image: mongo:4.0-xenial

    volumes:
      - ./property:/data/db
    ports:
      - 27017:27017
    networks:
      - networkOne

networks:
  networkOne:
